services:
  producer:
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_ACCESS_SECRET_KEY=${AWS_ACCESS_SECRET_KEY}
      - AWS_STREAM_NAME=${AWS_STREAM_NAME}
    image: kinesis_docker_study
    build:
      context: . 
      dockerfile: Dockerfile